# -*- coding: utf-8 -*-
"""pixabay.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15zsRvLr4lQBqCzR3ZxGNplp3QwcYG3Au
"""

!python -m spacy download en_core_web_lg

from google.cloud import storage
from google.oauth2 import service_account
projectname = 'profound-keel-253502'
bucketname = "avtech-pixabay"
keypath = "plumbing-key.json"

credentials = service_account.Credentials.from_service_account_file(keypath)
storage_client = storage.Client(credentials = credentials, project = projectname)
bucket = storage_client.get_bucket(bucketname)

import requests
x="https://cdn.pixabay.com/photo/2020/09/27/08/00/camels-5605985_1280.png"
response = requests.get(x)
filename=x.split("/")[-1]
file = open(filename, "wb")
file.write(response.content)
file.close()
blob = bucket.blob(filename)
blob.upload_from_filename(filename)

import pandas as pd 
df = pd.read_csv('pixabay.csv')
df.head()

for x in df["img_url_1280"]:
  response = requests.get(x)
  filename=x.split("/")[-1]
  file = open(filename, "wb")
  file.write(response.content)
  file.close()
  blob = bucket.blob(filename)
  blob.upload_from_filename(filename)